# Generated by Django 5.1.4 on 2024-12-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='major',
            field=models.CharField(max_length=100, null='non_major'),
            preserve_default='non_major',
        ),
    ]
