# Generated by Django 5.1.4 on 2024-12-13 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_role_in_school'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='all_users',
        ),
    ]
